### ISSUE TITLE
allow for custom file naming w/o creating all files/selectors (grunticon related)

### ISSUE THREAD

**Issue by zigotica** [filamentgroup/directory-encoder#13]
(hell, it's hard to title this)

I was going to post this at Grunticon issues but @jlembeck directed me here. Let's see if I can articulate this enhancement in an understandable way.

Imagine we have 2 SVG files, `a.svg` and `a-hover.svg`, the difference between the two being not just color but could be anything, shape, size, whatever.

By default Grunticon would create 2 selectors, one for each: `.icon-a{}` and `.icon-a-hover{}`, plus the corresponding fallback files.

That's ok but if we just want to use one for a default state and the other for a hover state, and `<a class='icon-a'>` in our markup, it can be hard without using JS to change classes.

I know we can use customselectors in our Grunticon gruntfile, but that can be a daunting task (pun intended) when having several of them. So I imagine there could be a way to name files and make grunticon/encoder to just generate those files/selectors that we need. Maybe a similar approach to the color naming convention, but in this case, just generating the state, not the generic file/selector?

In our ideal case, `a.states-hover.svg` would generate `.icon-a:hover` but not  `.icon-a{}` (to avoid overwriting it).

Does it make sense, and is it doable?
Thanx again for this great tool.

**Comment by zigotica** [comment]
hey @jefflembeck just a kind reminder, has this landed to Grunticon 2.x or is this planned for future releases? I know v2.0 can embed SVG + match elements inside them using CSS, but I think this would be slightly different (plus compatibility). 

Thank you so much again! <3

**Comment by zachleat** [comment]
This repository is now using [lodash style issue management](https://twitter.com/samselikoff/status/991395669016436736) for enhancements. This means enhancement issues will now be closed instead of leaving them open.

View [the enhancement backlog here](https://github.com/filamentgroup/directory-encoder/issues?utf8=%E2%9C%93&q=label%3Aneeds-votes+sort%3Areactions-%2B1-desc+). Don’t forget to upvote the top comment with 👍!
