### ISSUE TITLE
Move svg-uri-encoder to its own repo?

### ISSUE THREAD

**Issue by bfred-it** [filamentgroup/directory-encoder#17]
Unless there are alternative modules around the web it would be nice to move [svg-uri-encoder](https://github.com/filamentgroup/directory-encoder/blob/master/lib/svg-uri-encoder.js) to its own repo. That way it can be used elsewhere without depending on the whole `directory-encoder` (e.g. https://github.com/postcss/postcss-url/issues/18)

**Comment by jefflembeck** [comment]
I know you're looking for not depending on the whole of directory-encoder, but is there anything that's getting in your way? A folder of SVGs will just encode, and directory-encoder's png base64 section isn't exactly a big DL.

**Comment by bfred-it** [comment]
My only concern was that if you move/rename that file we don't have a link to it, but if it's in its own repo the file will always be referenced in package.json. But for now it's ok, we'll lock to the current version
