### ISSUE TITLE
Possibility to define Header/Footer?

### ISSUE THREAD

**Issue by MattDiMu** [filamentgroup/directory-encoder#21]
As far as I understood directory-encoder (which i use via grunticon - btw, I'm loving it!), I may specify a handlebar-template, which will be repeatedly used for each sourcefile, the output is then concatenated and a new file generated. In this newly generated file I'd like to be able to define some code before and after this list of handlebar-items.

Why? I'm using sass and instead of generating a list of css classes, i prefer to generate a sass-map with all data-uris, which i may use afterwards in mixins.

Another use case is documentation (I'm using Sassdoc). I'd like to be able to have some Comments on the top of this generated file. 

So instead of having a handlebar-template like this, which controls the output of each sourcefile
```
.{{name}} {
	background-image: url('{{datauri}}');
}
```

...I'd like to be able to control the output of the whole generated file, something like this:
```
/// some documentation for the whole file
$map: (
{{#each files}}
	{{this.name}}: {{this.datauri}}
{{/each}}
);
```

Any advice for me, how to achieve this?

Regards
Matthias

**Comment by jefflembeck** [comment]
So, we currently don't have a specific way to handle what you're looking for - but I'd be happy to add that (a prepend/append) functionality.
