### ISSUE TITLE
Expose Handlebars object for extension

### ISSUE THREAD

**Issue by bookwyrm** [filamentgroup/directory-encoder#28]
I've got a situation where I want to use the same set of SVG icons in both HTML (via data attributes) and CSS (via Sass magic). I figured out a way to [ab]use the [`previewTemplate`](https://gist.github.com/bookwyrm/f173b8c5bf5547ff2459) option to output a set of Sass lists where each list is comprised of a group of Sass variables which I then use like a standard image sprite via some Sass functions/mixins. These variables are built by [ab]using the [`template`](https://gist.github.com/bookwyrm/5ed3760fc9669e3d379c) option. This mostly works but I've run into an issue where I need the image type to be a part of the Sass variable name.

I figured that I could solve it by adding a [new helper](https://gist.github.com/bookwyrm/056d8464cc3525b5f4bc) to the `Handlebars` object in directory-coder.js but I didn't see any way that I could get access to the Handlebars object in order to extend it. I ended up just dropping my helper registration right into the `_loadTemplate` function which works for me on this one project but not moving forward.

Is there any way that the [Handlebars object](https://github.com/filamentgroup/directory-encoder/blob/master/lib/directory-encoder.js#L8) could be made available as some kind of a callback or something in the Gruntfile so that it can be extended easily?

**Comment by Aminta** [comment]
Hi @bookwyrm did you find a way to add a helper to Directory Encoder?

**Comment by bookwyrm** [comment]
@Aminta, not a clean way...I ended up just patching `directory-encoder.js` locally and updating my project documentation with a step to apply the patch.

```
--- lib/directory-encoder.js
+++ lib/directory-encoder.js
@@ -174,6 +174,15 @@
 
 		if( fs.existsSync( templateFile ) && fs.lstatSync( templateFile ).isFile() ){
 			var source = fs.readFileSync( templateFile ).toString( 'utf-8' );
+      Handlebars.registerHelper('data-type', function(arg) {
+        if ( arg.indexOf('image/svg') !== -1 ) {
+          return 'svg';
+        } else if ( arg.indexOf('image/png') !== -1 ) {
+          return 'png';
+        } else {
+          return 'png-fallback';
+        }
+      });
 			tmpl = Handlebars.compile(source);
 		} else {
 			throw new Error( "Template file either doesn't exist or isn't a file" );
```

`patch -p0 -d node_modules/directory-encoder < grunticon/directory-encoder.patch`

**Comment by Aminta** [comment]
Sorry @bookwyrm, me too I had added a new helper after var source = [...] but it return me a "Missing helper: " if I add my helper to .hbs file. I have to patch to make it working?

**Comment by Aminta** [comment]
Ok, it works, maybe previously I made a typo! Thanks for the hint!

**Comment by bookwyrm** [comment]
@Aminta you're welcome!

**Comment by Aminta** [comment]
By the way, in directory-encoder.js I've added
`	var Handlebars = require( 'handlebars' );
	var helpers = require('handlebars-helpers');`

after 

`var Handlebars = require( 'handlebars' );`

to use [Handlebar Helpers](https://github.com/assemble/handlebars-helpers#math) in my project and it works, if this can help...

**Comment by jefflembeck** [comment]
@bookwyrm sorry i'm late as ridiculously late to this as I am. Exposing the handlebars object doesn't sound like a bad idea. Unfortunately, as you might have guessed, i'm currently in no shape to make this change right now.

If you PR something in and make sure it passes tests, I would be completely happy to merge it, though.

**Comment by jmdrawneek** [comment]
@jefflembeck Is there anything I could do to help progress this? Would really love to add my own helper functions.

**Comment by zachleat** [comment]
Looks like this shipped? Closing.
