### ISSUE TITLE
Update handlebars because of security issues

### ISSUE THREAD

**Issue by danez** [filamentgroup/directory-encoder#29]
https://nodesecurity.io/advisories/61

**Comment by diegolacarta** [comment]
Same issue here, is this gonna be looked at? I can create a PR to fix it

**Comment by ricoli** [comment]
ping @jefflembeck ^^^^

**Comment by ricoli** [comment]
https://github.com/filamentgroup/directory-encoder/pull/30

**Comment by ricoli** [comment]
@jefflembeck now that it's merged in, could you make a new tag?

**Comment by ricoli** [comment]
ping @jefflembeck ^^^^^^^^^^^^

**Comment by jefflembeck** [comment]
This has been in for a long while. Closing.
