### ISSUE TITLE
IE8 maxlength Data URI fix could be improved!

### ISSUE THREAD

**Issue by zachleat** [filamentgroup/directory-encoder#32]
Looks like the [fix for the IE8 Data URI maxlength bug](https://github.com/filamentgroup/grunticon/issues/75) applies to all CSS output, in that my `icons.data.svg.css` file contains an external link to a PNG image.

![image](https://cloud.githubusercontent.com/assets/39355/20856638/93ac68e6-b8d9-11e6-8985-4267b143252a.png)

In my opinion this maxlength fix should only be applied to `icons.data.png.css`. IE8 should never see the `icons.data.svg.css` file loaded.

**Comment by jefflembeck** [comment]
I strongly agree with this suggestion. Would ❤️ a PR 😀
